### PR TITLE
4xx and 5xx error levels discriminated from each other.

### PR DESCRIPTION
**Pull request by feyyazesat**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Surely this is the wrong way around?

**Comment by GrahamCampbell** [comment]
4xx is worse than 5xx because it means the client made a mess. 5xx is just a temp server fault.

**Comment by feyyazesat** [comment]
@GrahamCampbell  4xx is stand for there is a client request problem. For example 403, 401 they are restrictions I think they are not critical errors, I focused to 404 more, and if there is no resource then it is 404, it is even not an error in the context. I want to listen 5xx errors on my rest api server and send to slack, it is a pain now. There are more than 10 critical level errors per second logging in to slack channel all of them are 404. So I also think it is not a correct way to discriminate them in this way, I think it should be more detailed.  But if you have better idea I would like to hear that and I can make a revision.

**Comment by GrahamCampbell** [comment]
> 4xx is stand for there is a client request problem. For example 403, 401 they are restrictions I think they are not critical errors

Yes they are in the context of a PHP application. If your code is causing the other server to respond with 4xx, then it's probably broken. If the other server responds with 5xx, then your code is totally fine.

**Pull request closed without merging**
